### ISSUE TITLE
base,enviro   not find package?

### ISSUE THREAD

**Issue by zxtchiu** [rock-planning/planning-vfh_star#2]
why did  i  not find the package base and enviro??
it is important for the program!!! 
thanks

**Comment by doudou** [comment]
This package is part of the Rock framework (www.rock-robotics.org). You can build it separately from the rest of the framework, but you will then have to checkout and manually build its dependencies.

The dependencies from this package are defined in its `manifest.xml` file. See https://www.rock-robotics.org/documentation/packages/outside_of_rock.html for more information
